{% metadata_file .yamato/test_versions.metafile %}
---
{% for editor in test_editors %}
test_linux_training_int_{{ editor.version }}:
  name: Test Linux Fast Training {{ editor.version }}
  agent:
    type: Unity::VM
    image: ml-agents/ml-agents-ubuntu-18.04:latest
    flavor: b1.medium
  variables:
    UNITY_VERSION: {{ editor.version }}
  commands:
    - |
      eval "$($HOME/anaconda/bin/conda shell.bash hook)"
      conda activate python3.7
      python -m pip install pyyaml --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple
      python -u -m ml-agents.tests.yamato.training_int_tests
  dependencies:
    - .yamato/standalone-build-test.yml#test_linux_standalone_{{ editor.version }}
  triggers:
    cancel_old_ci: true
    expression: |
      (pull_request.target eq "main" OR
      pull_request.target match "release.+") AND
      NOT pull_request.draft AND
      (pull_request.changes.any match "com.unity.ml-agents/**" OR
      pull_request.changes.any match "com.unity.ml-agents.extensions/**" OR
      pull_request.changes.any match "Project/**" OR
      pull_request.changes.any match "ml-agents/**" OR
      pull_request.changes.any match "ml-agents-envs/**" OR
      pull_request.changes.any match ".yamato/training-int-tests.yml") AND
      NOT pull_request.changes.all match "**/*.md"
  artifacts:
    logs:
      paths:
        - "artifacts/standalone_build.txt"
        - "artifacts/inference.nn.txt"
        - "artifacts/inference.onnx.txt"
    standalonebuild:
      paths:
        - "artifacts/testPlayer*/**"
        - "artifacts/models/**"
{% endfor %}
